@csrf
<div class="space-y-5 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
    <div><label for="title" class="block text-sm font-semibold">Título</label><input id="title" name="title" value="{{ old('title', $entry?->title) }}" required maxlength="255" class="mt-2 block w-full rounded-lg border-slate-300">@error('title')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="content" class="block text-sm font-semibold">Contenido</label><textarea id="content" name="content" rows="10" required maxlength="50000" class="mt-2 block w-full rounded-lg border-slate-300">{{ str_replace('\\n', "\n", old('content', $entry?->content)) }}</textarea>@error('content')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="source" class="block text-sm font-semibold">Fuente</label><input id="source" name="source" value="{{ old('source', $entry?->source) }}" maxlength="1000" class="mt-2 block w-full rounded-lg border-slate-300">@error('source')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="category" class="block text-sm font-semibold">Categoría</label><select id="category" name="category" class="mt-2 block w-full rounded-lg border-slate-300"><option value="fact" @selected(old('category', $entry?->category ?? 'fact') === 'fact')>Hecho</option><option value="product" @selected(old('category', $entry?->category) === 'product')>Producto</option><option value="price" @selected(old('category', $entry?->category) === 'price')>Precio</option><option value="policy" @selected(old('category', $entry?->category) === 'policy')>Política</option><option value="restriction" @selected(old('category', $entry?->category) === 'restriction')>Restricción</option><option value="contact" @selected(old('category', $entry?->category) === 'contact')>Contacto</option><option value="brand_identity" @selected(old('category', $entry?->category) === 'brand_identity')>Identidad de marca</option><option value="future_idea" @selected(old('category', $entry?->category) === 'future_idea')>Idea futura</option></select>@error('category')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="applicability" class="block text-sm font-semibold">Aplicabilidad</label><select id="applicability" name="applicability" class="mt-2 block w-full rounded-lg border-slate-300"><option value="global" @selected(old('applicability', $entry?->applicability ?? 'global') === 'global')>Global</option><option value="price" @selected(old('applicability', $entry?->applicability) === 'price')>Precios</option><option value="location" @selected(old('applicability', $entry?->applicability) === 'location')>Ubicación</option><option value="delivery" @selected(old('applicability', $entry?->applicability) === 'delivery')>Entrega</option><option value="order" @selected(old('applicability', $entry?->applicability) === 'order')>Pedido</option><option value="customer_service" @selected(old('applicability', $entry?->applicability) === 'customer_service')>Atención al cliente</option><option value="content" @selected(old('applicability', $entry?->applicability) === 'content')>Contenido</option></select>@error('applicability')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="status" class="block text-sm font-semibold">Estado</label><select id="status" name="status" class="mt-2 block w-full rounded-lg border-slate-300"><option value="pending" @selected(old('status', $entry?->status) === 'pending')>Pendiente</option><option value="verified" @selected(old('status', $entry?->status) === 'verified')>Verificado</option><option value="archived" @selected(old('status', $entry?->status) === 'archived')>Archivado</option></select></div>
    <button type="submit" class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Guardar conocimiento</button>
</div>